version: "3.8"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/galatea
    depends_on:
      db:
        condition: service_healthy  # Espera a que PostgreSQL esté listo
    restart: always

  db:
    image: postgres:15
    container_name: galatea_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: galatea
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 3s
    restart: always

volumes:
  db_data: